# .streamlit/secrets.toml - VERSION CORRIGÉE ET TESTÉE

[DEEPSEEK]
API_KEY = "sk-da3c2fde36b14f108e8cdb73e73e885f"

[GITHUB]
TOKEN = "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"
REPO_OWNER = "zekobiceps"
REPO_NAME = "TG_Hire"

[GCP_SERVICE_ACCOUNT]
type = "service_account"
project_id = "astute-anchor-418600"
private_key_id = "a746bd2519769b7e7bf4068b1874c415f9c94fab"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDdHmkxnpHOs55A
YX1lDjh8sFJ5q4EVeXa4ATrCO6EgU2GJWmmCKIUH/D5/HK7L8GBZUuYIucFBD+8n
S3TZw6+n8P+TGGWuhrmyjCRgKUg8ZUmeRs+qjH0E1D65uxbUCf3L9K74dvqPDKav
JLwI9RG6Uxq17zer4lsWM89gDqzvpBoMphg6/N4jwPC/ctT1636PsHHEykCRCiKh
tIqho4F0ZKdmtL3GT9YwHrePZi89gn12idWWFZSCe/z++4Ca1GBN37Qe7acow16f
mvNEobYkq+4EGOc0r2bRxSojBp3H7V3TD0rN9hPx1HL3BRKIkpGOMdKvfkv9zPU7
POxcV0PvAgMBAAECggEALFQk7aQnAgPjZW/F9kTwERs+JZM66SW1JbVlZLwUlMjy
hFlCTqw140Bv/QawikUR48ZpRHWM5zC9Fqkbb266H9aCPiiFdgQfZUqQHlEYYLdD
l34FsuDATYAJZS27KV4pacKPc1NS7uuv3Ovl4HvVBoATmkavZ/+UmDJh0BWRGOdz
QN6BPy3L/7J6xeqLpX7PEPQue1pOpfwgM52XZqy4yf7cttZKK4AoDKSnLrU8SG7s
Tz1+dheAyOyrzQE4PyR6jFglLAbOKUYkNt9YkIw1zkLD+TaRw/oZLbBqGhMV50VI
PSDjgC6gFjQuZr+FOThP3crmzOulikOVuetUesESeQKBgQDy7n3YF2wZXP5wvrDk
smAEaR+7HB3nr849rkeLuGreKwdyIPVqTz40h9U4TpSHRGTUAnKHuSxB4k9T5xSU
0nU6vnBfubooBE+UoRUtf+sxrp7Z8qIFn7Mmde9aeI2IOO4TYnzj0n8Xw7rvaKXR
5rwaNXvRZHoEs2xKE9dJ5tnD9wKBgQDpA4a9S6KOA8RQCxkGNmw48xxuEWDkgGs1
l+t4go3JafgFFTX6ZRGA/EMmAZK6/KX46LN/3mmVVUGuHfOewyU3BaUY8a+6QerD
UghrNxo2vzSAS+hwRIaeflm/Di6xJZnLcKg2gL9gFOGXN7SgFUi2kolQpeT8nflw
T1lt7S8RyQKBgQDTKwypMnL8+SET0C7kHUnpi5fRhfdY1jFo3H3ErmH3DWBDjPLH
nmpsL0bg0y25B3K9+AKmiAg4nQhn3o69btQIZFI6Y6+16Ulj4UIPcwp2/VuICKle
ShvoasvM0M32g8Yvg4UcZHWlqrZsNYMummsYPTWMJtMKEw0mt2iFDO5usQKBgQCk
C4qBnE0eBELiQ13jxM7eLTHXv75iQJK50XHCjs85fLRTB8LPvPXcxDyV9keSAyrq
GRG+NRxKORKbfZS1MhfyK7Q24nhf/eZEim1I5is7XdOde1NyLpxD2xpd6qMurhUf
Z/nVHUEeaLUFm/87MKDXgETSFWkn/CPPUN3aCUC5GQKBgQDtopFYi66sm8syKTPb
i6C5MCs04HWLKtwq3iwzk6u20/KpkU77/mDk/er/3zWHB43eBy559qGRIiCRw6VW
uI6iW8UDB1hkw8D6ww0X67IxTG4LQsRXEyi2u/0J8GjMPCksZWDm/vIbbiHTIBdg
xFSCq2ZVavwXRLKlCTQjBS8E0A==
-----END PRIVATE KEY-----"""
client_email = "tg-hire@astute-anchor-418600.iam.gserviceaccount.com"
client_id = "105746123909483274099"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tg-hire%40astute-anchor-418600.iam.gserviceaccount.com"
universe_domain = "googleapis.com"