# .streamlit/secrets.toml - Version simplifiée
DEEPSEEK_API_KEY = "sk-da3c2fde36b14f108e8cdb73e73e885f"
GITHUB_TOKEN = "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"
REPO_OWNER = "zekobiceps"
REPO_NAME = "TG_Hire"